# Generated by Django 2.2.4 on 2019-09-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_chatcontact_is_current'),
        ('webrtc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.ChatRoom'),
        ),
    ]
