# Generated by Django 2.2.4 on 2019-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190904_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
