# Generated by Django 2.2.4 on 2019-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_userphoto_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
