# Generated by Django 2.2.4 on 2019-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_userphoto_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
