# Generated by Django 2.2.4 on 2019-09-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_moderation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='moderation',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
