# Generated by Django 2.2.4 on 2019-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_auto_20190926_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='New or not?'),
        ),
    ]
