# Generated by Django 2.2.4 on 2019-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_moderation_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='type_obj',
            field=models.CharField(choices=[('woman-profile', 'Woman profile'), ('man-profile', 'Man profile'), ('agency', 'Agency'), ('photo', 'Photo'), ('video', 'Video')], default='woman-profile', max_length=20, verbose_name='Object type'),
        ),
    ]
