# Generated by Django 2.2.4 on 2019-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_moderation_type_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='type_obj',
            field=models.CharField(choices=[('woman-profile', 'Woman profile'), ('man-profile', 'Man profile'), ('agency', 'Agency'), ('photo-new', 'New photo'), ('photo-delete', 'Delete photo'), ('photo-main', 'Main photo'), ('video', 'Video')], default='woman-profile', max_length=20, verbose_name='Object type'),
        ),
    ]
