# Generated by Django 2.2.4 on 2019-10-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_auto_20190930_2116'),
        ('moderation', '0008_auto_20190930_0958'),
    ]

    operations = [
    ]
