# Generated by Django 2.2.4 on 2019-09-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='name_en',
            field=models.CharField(help_text='Name', max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='props',
            name='name_ru',
            field=models.CharField(help_text='Name', max_length=250, null=True, verbose_name='Name'),
        ),
    ]
