# Generated by Django 2.2.4 on 2019-09-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0004_props_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='props',
            options={'verbose_name': 'User property', 'verbose_name_plural': 'User properties'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'verbose_name': 'User property value', 'verbose_name_plural': 'User property values'},
        ),
    ]
