# Generated by Django 2.2.4 on 2019-08-31 10:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_useronline_sid'),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about_me', models.TextField(help_text='About me', verbose_name='About me')),
                ('gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], db_index=True, default='male', max_length=6, verbose_name='Gender')),
                ('hight', models.IntegerField(help_text='Hight')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='woman',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Man',
        ),
        migrations.DeleteModel(
            name='Woman',
        ),
    ]
