# Generated by Django 2.2.4 on 2019-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190831_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hight',
            field=models.IntegerField(help_text='Hight', null=True),
        ),
    ]
