# Generated by Django 2.2.4 on 2019-09-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
