# Generated by Django 2.2.4 on 2019-09-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lang',
            new_name='language',
        ),
    ]
