# Generated by Django 2.2.4 on 2019-09-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190921_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('repl_amount', models.FloatField(default=0)),
                ('user_profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
