# Generated by Django 2.2.4 on 2019-09-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_replenishmentlog'),
        ('account', '0009_remove_userprofile_country'),
    ]

    operations = [
    ]
