# Generated by Django 2.2.4 on 2019-10-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_replanishmentplan'),
        ('account', '0013_remove_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replenishmentlog',
            name='repl_amount',
        ),
        migrations.AddField(
            model_name='replenishmentlog',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.ReplanishmentPlan'),
        ),
    ]
