# Generated by Django 2.2.4 on 2019-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191003_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zodiac',
            field=models.CharField(default='', max_length=50),
        ),
    ]
