# Generated by Django 2.2.4 on 2019-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplates',
            name='alias',
            field=models.CharField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='content_en',
            field=models.TextField(help_text='Content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='content_ru',
            field=models.TextField(help_text='Content', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mailtemplates',
            name='title_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
