# Generated by Django 2.2.4 on 2019-09-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20190920_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
