# Generated by Django 2.2.4 on 2019-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='alias',
            field=models.CharField(max_length=250),
        ),
    ]
