# Generated by Django 2.2.4 on 2019-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20190927_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplanishmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dollar', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
    ]
