# Generated by Django 2.2.4 on 2019-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_replanishmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='type_obj',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
