# Generated by Django 2.2.4 on 2019-09-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
    ]
