# Generated by Django 2.2.4 on 2019-09-26 07:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20190926_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=django_countries.fields.CountryField(default='UA', max_length=2),
        ),
    ]
