# Generated by Django 2.2.4 on 2019-09-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_agency2woman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency2woman',
            options={'verbose_name': 'Agency woman', 'verbose_name_plural': 'Agency women'},
        ),
        migrations.AlterModelOptions(
            name='agencyfiles',
            options={'verbose_name': 'Agency file', 'verbose_name_plural': 'Agency files'},
        ),
    ]
