# Generated by Django 2.2.4 on 2019-09-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20190926_0900'),
        ('agency', '0006_auto_20190926_0906'),
    ]

    operations = [
    ]
