# Generated by Django 2.2.4 on 2019-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_merge_20190926_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.CharField(default='', max_length=250, verbose_name='Country'),
        ),
    ]
