# Generated by Django 2.2.4 on 2019-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronline',
            name='sid',
            field=models.CharField(db_index=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
