# Generated by Django 2.2.4 on 2019-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_useronline_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronline',
            name='agent',
            field=models.CharField(db_index=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
