# Generated by Django 2.2.4 on 2019-09-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_useronline_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronline',
            name='sid',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
