# Generated by Django 2.2.4 on 2019-09-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_useronline_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronline',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
