# Generated by Django 2.2.4 on 2019-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_useronline_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronline',
            name='sid',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
