# Generated by Django 2.2.4 on 2019-09-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20190909_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='room',
        ),
    ]
