# Generated by Django 2.2.4 on 2019-09-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_is_online'),
        ('room', '0005_chatmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='abonent',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='owner',
        ),
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonent', to='account.UserProfile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.UserProfile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.ChatRoom')),
            ],
        ),
    ]
