# Generated by Django 2.2.4 on 2019-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20190910_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontact',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
