# Generated by Django 2.2.4 on 2019-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_chatcontact_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontact',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatcontact',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
