# Generated by Django 2.2.4 on 2019-09-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20190925_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Chat room', 'verbose_name_plural': 'Chat rooms'},
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Is suspended?'),
        ),
    ]
