# Generated by Django 2.2.4 on 2019-09-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_auto_20190925_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
