# Generated by Django 2.2.4 on 2019-09-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_chatmessage_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='timer',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
