# Generated by Django 2.2.4 on 2019-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_chatroom_is_low_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_suspended',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Is answered?'),
        ),
    ]
