# Generated by Django 2.2.4 on 2019-09-25 06:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_remove_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alias', max_length=250, verbose_name='Alias')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='User')),
                ('name', models.CharField(help_text='Name', max_length=250, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='User')),
                ('type', models.CharField(help_text='Type', max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='account.UserProfile')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='account.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'User payments',
                'verbose_name': 'User payment',
            },
        ),
    ]
