# Generated by Django 2.2.4 on 2019-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
    ]
