# Generated by Django 2.2.4 on 2019-10-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_merge_20190926_1529'),
        ('payment', '0002_payment_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='agency.Agency'),
        ),
    ]
